version: '3'
services:
    app:
        build:
            context: .
            dockerfile: ./build/Dockerfile
        volumes:
            -   ./app:/go/src/app
        tty: true
        env_file:
            -   .env
        networks:
            -   go-todo-network
        ports:
            -   '4000:3000'
        depends_on:
            -   db

    db:
        image: mariadb:10.9.3
        container_name: mariadb
        env_file:
            -   .env
        ports:
            -   "3306:3306"
        volumes:
            -   ./db:/var/lib/mysql
        networks:
            -   go-todo-network
        tty: true
volumes:
    mariadb:

networks:
    go-todo-network:
        external: true
